### ISSUE TITLE
Reference to Nonexistent Variable

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/thinkcspy#62] opened 2017-02-01 20:00 UTC
In this chapter, there is an active code block accompanied by an explanation, which mentions a variable called `newimg`. But the code sample does not actually have a variable called `newimg`.

http://127.0.0.1:8000/runestone/static/thinkcspy/MoreAboutIteration/2DimensionalIterationImageProcessing.html

**Comment by seraries** [comment] 2017-04-05 16:46
Closing this issue as it is a duplicate of issue #33

**Closed as completed by seraries** 2017-04-05 16:46 UTC
